gh-1763 Documentation guidelines: description of adding a submodule
tarantool/doc pull request #1819
Opened 2021-02-11 08:05 UTC by veod32

Add a new section in the  Documentation guidelines related to documentation infrastructure with the description of adding a submodule into the documentation repository.

Closes #1763

2021-02-11 08:47 UTC, artembo approved these changes

2021-02-11 09:10 UTC, NickVolynkin requested changes

2021-02-11 09:10 UTC, NickVolynkin commented on doc/contributing/docs/doc_infrastructure.rst
> +``metrics``
Очень круто, что ты разбираешь аж на двух примерах, как у нас всё устроено и почему именно так.

2021-02-11 09:10 UTC, NickVolynkin commented on doc/contributing/docs/doc_infrastructure.rst
> +   monitoring_root="${project_root}/modules/metrics/doc/monitoring" #
решетка в конце строки не нужна )

2021-02-11 09:10 UTC, NickVolynkin commented on doc/contributing/docs/doc_infrastructure.rst
> +   monitoring_root="${project_root}/modules/metrics/doc/monitoring" #
А вместо копирования кода можно было бы включить куски прямо из update_submodules.sh https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude

2021-02-11 09:10 UTC, NickVolynkin commented on doc/contributing/docs/doc_infrastructure.rst
> +body of Tarantool documentation presented at the `official web-site <http://www.tarantool.io/en/doc>`_.
лучше https, и можно дать ссылку без языка, чтобы нужный язык выбрался сам: https://www.tarantool.io/doc

2021-02-12 06:38 UTC, veod32 commented on doc/contributing/docs/doc_infrastructure.rst
> +   :local:
https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents

local : flag (empty)
Generate a local table of contents. Entries will only include subsections of the section in which the directive is given. If no explicit title is given, the table of contents will not be titled.

2021-02-12 12:29 UTC, NickVolynkin commented on doc/contributing/docs/doc_infrastructure.rst
> +   :local:
Круто, не знал про такую штуку.

2021-02-12 13:54 UTC, merged