gh-1825 Add tntcxx submodule and publish C++ connector Getting started
tarantool/doc pull request #1852
Opened 2021-02-20 14:11 UTC by veod32

Part of #1825

2021-02-20 16:43 UTC, NickVolynkin requested changes

2021-02-20 16:43 UTC, NickVolynkin commented on .gitignore
> +/doc/getting_started/getting_started_cxx.rst
Зря тут дублирование в пути. Давай файл назовем просто cxx.rst? Остальные потом тоже переименуем.

2021-02-20 16:43 UTC, NickVolynkin commented on .gitignore
> +/doc/getting_started/_includes/
У нас же уже есть файлы в этой директории? Если и нет, то может появиться. Если что-то приходит из tntcxx, пусть оно ложится в директорию cxx или cxx/_includes.

2021-02-20 16:43 UTC, NickVolynkin commented on update_submodules.sh
> +tntcxx_api_dest="${project_root}/doc/book/connectors/"
А это пока что не копируем, да?

2021-02-20 16:43 UTC, NickVolynkin commented on update_submodules.sh
> +yes | cp -rf "${tntcxx_root}/examples/" "${tntcxx_gs_dest}/_includes/"
Тут можно сначала создать директорию getting_started/cxx/, а потом в нее копировать examples как _includes

2021-02-24 12:43 UTC, veod32 commented on update_submodules.sh
> +tntcxx_api_dest="${project_root}/doc/book/connectors/"
пока не копируем контент по API сюда, т.к. он еще в драфтовом виде.
tntcxx_api_dest="${project_root}/doc/book/connectors/"

2021-02-24 12:45 UTC, veod32 commented on .gitignore
> +/doc/getting_started/getting_started_cxx.rst
сделал файл cxx.rst

2021-02-24 12:48 UTC, veod32 commented on update_submodules.sh
> +yes | cp -rf "${tntcxx_root}/examples/" "${tntcxx_gs_dest}/_includes/"
давай пока так оставим на эту итерацию. Если сейчас поменять структуру, нужно в нескольких местах это исправлять, в т.ч. в сорсах документа.

2021-02-24 12:49 UTC, veod32 commented on .gitignore
> +/doc/getting_started/_includes/
давай пока так оставим на эту итерацию. Если сейчас поменять структуру, нужно в нескольких местах исправлять пути, в т.ч. в сорсах документа.

2021-02-24 12:59 UTC, merged