Reformat PO and POT files for minimal diff
tarantool/doc pull request #2054
Opened 2021-04-13 10:09 UTC by NickVolynkin

Co-authored-by: Artem Morozov <artembo@me.com>

2021-04-13 13:34 UTC, artembo commented
I see two issues:
1. The changes in pot-files seems to be redundant. I would live pot files without modification if it is possible.
2. We have to avoid adding empty metadata to po files. Please see diff in #2056

2021-04-13 13:50 UTC, Onvember approved these changes

2021-04-13 13:54 UTC, artembo requested changes
@NickVolynkin
I see two issues:

1. The changes in pot-files seems to be redundant. I would live pot files without modification if it is possible.
2. We have to avoid adding empty metadata to po files. Please see diff in #2056

2021-04-16 04:52 UTC, NickVolynkin commented on locale/cleanup.py
> +        cleanup_files('pot')
We shall completely remove POT files in the next step.

2021-04-16 04:58 UTC, merged