gs: introduce the raw version
tarantool/doc pull request #2228
Opened 2021-07-07 10:45 UTC by artur-barsegyan

Closed #2227

2021-07-14 07:49 UTC, NickVolynkin commented on doc/getting_started/index.rst
> -   getting_started_db
Там были три дочерних документа, сейчас они просто пропали.

2021-08-14 15:07 UTC, artur-barsegyan commented on doc/getting_started/index.rst
> -   getting_started_db
Я добавил новых коммитов и теперь это связная история. 

Я рассказываю про эти разделы, но в данном туторе осознанно делаю упор сразу на кластерное решение.

При ревью, обрати пожалуйста внимание на доступность старых разделов. Как тебе кажется, не станет ли кому-то из пользователей сильно неудобно/непонятно?

2021-08-14 16:52 UTC, ligurio requested changes

2021-08-14 16:52 UTC, ligurio commented on doc/getting_started/getting_started_beggining.rst
> +``sharding_key``. ``sharding_key`` указывает на поле в спейсе, по
sharding key может состоять из нескольких полей

2021-12-21 08:52 UTC, artur-barsegyan commented
So, there is no right way to merge text in Russian via PR. We are already pushed that GS in English.

Russian translation will be pushed via Crowdin.

2021-12-21 08:52 UTC, closed without merging