Document return_raw net.box option
tarantool/doc pull request #2739
Opened 2022-03-04 15:39 UTC by xuniq

Fixes #2506

2022-03-05 10:45 UTC, locker approved these changes

2022-03-09 06:08 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +* ``{buffer=...}``. For example, see :ref:`buffer module <buffer-module>`.
```suggestion
* ``{buffer=...}``. For an example, see the :ref:`buffer module <buffer-module>`.
```
This means "for an example of this option", not just idiomatically "for example".

2022-03-09 06:13 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +* (since version 2.10.0) ``return_raw`` = ``true|false`` (default = ``false``).
Please rewrite this in consistency with all the other options: {return_raw=...}

2022-03-09 06:13 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +  For example, see :ref:`return_raw <net_box-return_raw>`.
```suggestion
  For an example, see :ref:`return_raw <net_box-return_raw>`.
```

2022-03-09 06:14 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +            local mp = c.eval('eval ...', {1, 2, 3}, {return_raw = true})
Do we need spaces around the `=` sign? Will it work?

2022-03-09 06:17 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +            ``begin``, ``commit``, ``rollback``, ``upsert``, ``prepare``;
```suggestion
        ``{return_raw=true}`` is ignored for:
        
        *   Methods that return ``nil``: ``begin``, ``commit``, ``rollback``, ``upsert``, ``prepare``
```

The asterisk now looks as, well, an asterisk.
Please refer to our [list punctuation style guide](https://www.tarantool.io/en/doc/latest/contributing/docs/style/#ending-punctuation-in-lists-and-tables). The rules in English and Russian are different.

2022-03-09 06:18 UTC, patiencedaur requested changes
Left some comments.

2022-03-09 12:18 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +* ``{return_raw=...`` (since version 2.10.0).
```suggestion
* ``{return_raw=...}`` (since version 2.10.0).
```
Missing bracket

2022-03-09 12:20 UTC, patiencedaur commented on doc/reference/reference_lua/net_box.rst
> +  For an example, see :ref:`return_raw <net_box-return_raw>`.
```suggestion
  For an example, see option description :ref:`below <net_box-return_raw>`.
```

2022-03-09 12:24 UTC, patiencedaur approved these changes

2022-03-09 12:33 UTC, merged