Document `vshard.router.map_callrw()`
tarantool/doc pull request #2753
Opened 2022-03-16 10:04 UTC by xuniq

Fixes #2015

2022-03-29 16:22 UTC, veod32 requested changes

2022-03-29 16:22 UTC, veod32 commented on doc/reference/reference_rock/vshard/vshard-router.rst
> +    Consistency, defined for map-reduce, is not compatible with rebalancing.
The idea is not clear. Try to re-write.

2022-03-29 21:04 UTC, Gerold103 reviewed
Thanks for the patch!

2022-03-29 21:04 UTC, Gerold103 commented on doc/reference/reference_rock/vshard/vshard-router.rst
> +    For this, the storage has a special scheduler for bucket moves and storage refs.
Storage ref is a volatile counter defined on each instance. It is incremented when a map-reduce request comes and decremented when it ends. It is almost the same as bucket ref, but it pins the entire instance with all its buckets, not just a single bucket.

2022-04-08 13:38 UTC, xuniq commented on doc/reference/reference_rock/vshard/vshard-router.rst
> +    It can be configured using storage options ``sched_move_quota`` and ``sched_ref_quota``.
https://github.com/tarantool/doc/issues/2014

2022-04-12 12:06 UTC, veod32 commented on doc/reference/reference_rock/vshard/vshard-router.rst
> +    It can be configured using the storage options ``sched_move_quota`` and ``sched_ref_quota``.
Make :ref: links to the description of these options

2022-04-12 12:06 UTC, veod32 approved these changes

2022-04-12 12:43 UTC, merged