Add tt check
tarantool/doc pull request #3051
Opened 2022-07-26 05:58 UTC by p7nov

Resolves #2557

2022-08-02 09:14 UTC, LeonidVas approved these changes
LGTM

2022-08-02 12:05 UTC, patiencedaur requested changes
One important note. Everything else LGTM :)

2022-08-02 12:05 UTC, patiencedaur commented on doc/reference/tt_cli/connect.rst
> +        :widths: 20 80
Let's select different column widths.

![image](https://user-images.githubusercontent.com/40490252/182370077-100f490f-b44d-4bb2-a595-b4b4c9d2cfdf.png)

2022-08-03 04:59 UTC, patiencedaur approved these changes

2022-08-03 05:23 UTC, merged