MessagePack extensions for the datetime and interval types
tarantool/doc pull request #3077
Opened 2022-08-09 15:15 UTC by xuniq

Fixes #3060

2022-08-16 22:10 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +    | MP_EXT | length (optional) | MP_DECIMAL | PackedDecimal |
Wrong picture - it's supposed to be datetime, not decimal.

2022-08-16 22:11 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +    | MP_EXT | length (optional) | MP_INTERVAL | PackedDecimal |
Again, it's depicting decimal, not interval.

2022-08-16 22:12 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +    |0xd7/0xd8|type (4)| seconds (8b)  | nsec; tzoffset; tzindex; (8b) |
Oh, now it's much better, and is more relevant!

2022-08-16 22:15 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +(strictly speaking - they has nothing in common whatsoever).
> (strictly speaking - they has nothing in common whatsoever)

I'd remove this part from official documentation.

2022-08-16 22:27 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +``scale`` = number of digits after the decimal point
Which `scale`?

2022-08-16 22:28 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +``BCD`` is a sequence of bytes representing decimal digits of the encoded number
`BCD` ? Smells like copy-paste from decimal

2022-08-16 22:29 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +*   Seconds (8b) as full, unencoded, signed 64-bit integer, stored in little-endian order.
`Seconds (8 bytes)`

2022-08-16 22:30 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> +*   The optional fields (8b), if any of them have a non-zero value.
`The optional fields (also 8 bytes)...`

2022-08-16 22:32 UTC, tsafin commented on doc/dev_guide/internals/msgpack_extensions.rst
> -``PackedInterval`` has the following structure:
In this commit this confusing copy/paste has been deleted. Nice!

2022-08-16 22:34 UTC, tsafin requested changes
Sorry for the confusing references - I've commented some particular commits inside of pull-request, and sometimes those comments have already been resolved till the end. But there are some complaints which are still active.

2022-08-17 06:35 UTC, veod32 requested changes

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +It creates a container of 8 or 16 bytes long payload.
"long payload" -- is it a term, or we just mean "8 or 16 bytes long"? If the second case, please rephrase.

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +defines ``d7``to mean ``fixext`` with size 8 or ``d8`` to mean ``fixext`` with size 16.
```suggestion
defines ``d7`` to mean ``fixext`` with size 8 or ``d8`` to mean ``fixext`` with size 16.
```

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +The `MessagePack spec <https://github.com/msgpack/msgpack/blob/master/spec.md>`_
```suggestion
The `MessagePack specification <https://github.com/msgpack/msgpack/blob/master/spec.md>`_
```

It's better not to use slang terms.

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +*   Seconds (8b) as full, unencoded, signed 64-bit integer, stored in little-endian order.
"as full" -- what does it mean?

Please also correct the punctuation and articles.

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +    The fields include nsec, tzoffset, and tzindex, packed in little-endian order.
```suggestion
    The fields include ``nsec``, ``tzoffset``, and ``tzindex`` packed in the little-endian order.
```

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +For more information about datetime, see :ref:`datetime field type details <index-box_datetime>`
"For more information about datetime, ..."

There should be "the datetime type" or something similar -- there's no such word/entity as just "datetime".

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +and :doc:`module datetime </reference/reference_lua/datetime>`.
> and :doc:`module datetime </reference/reference_lua/datetime>`

Better to say, "description of the datetime module" or "reference for the datetime module".

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +The interval is saved as variant of a map with predefined number of known attributes names.
Correct articles.

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +*   packed non-null fields
```suggestion
*   packed non-null fields.
```

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +Some attributes might be undefined. In this case, they will be omitted from the generated payload.
> might be

Do we really need to use this modal verb?

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +Interval value ``1 year, 200 months, -77 days`` is encoded in the following way:
```suggestion
Interval value ``1 years, 200 months, -77 days`` is encoded in the following way:
```

2022-08-17 06:35 UTC, veod32 commented on doc/dev_guide/internals/msgpack_extensions.rst
> +and :doc:`module datetime </reference/reference_lua/datetime>`.
The same comment as to the last sentense in the section for the DATETIME type.

2022-08-19 11:01 UTC, tsafin approved these changes
LGTM, Thanks!

2022-08-22 11:31 UTC, veod32 approved these changes

2022-08-22 15:29 UTC, merged