Update Python connector comparison table
tarantool/doc pull request #3212
Opened 2022-11-09 12:18 UTC by DifferentialOrange

- Add new features from tarantool-python 0.10.0 [1].
- Add links to tarantool-python and asynctnt related issues.
- Add Interval and encryption support comparison row [2, 3].
- Remove obsolete comments.
- Change order in some comments based on current strategy:
  - pip is more preferable than deb and rpm,
  - readthedocs is up-to-date and more thorough source of information now [1].
- Reorder extension types order based on their documentation order [2].
- Update stars counter.

1. https://github.com/tarantool/tarantool-python/releases/tag/0.10.0
2. https://www.tarantool.io/en/enterprise_doc/security/#enterprise-iproto-encryption
3. https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/

2022-11-09 17:50 UTC, xuniq approved these changes
Added several suggestions about formatting.
If possible, we usually use `:doc:` and :`ref:` (anchor) directives for link formatting. Fpr more information, refer to the style guide: https://www.tarantool.io/en/doc/latest/contributing/docs/markup/links/

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +            <https://www.tarantool.io/en/doc/latest/getting_started/getting_started_python/>`__)
```suggestion
            and :ref:`tarantool.io <getting_started-python>`)
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +        -   `pip, deb, rpm, <https://github.com/tarantool/tarantool-python#download-and-install>`__
```suggestion
        -   `pip, deb, rpm <https://github.com/tarantool/tarantool-python#download-and-install>`__
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `Decimal support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-decimal-type>`__
```suggestion
    *   -   :ref:`Decimal support <msgpack_ext-decimal>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `UUID support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-uuid-type>`__
```suggestion
    *   -   :ref:`UUID support <msgpack_ext-uuid>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `EXT_ERROR support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-error-type>`__
```suggestion
    *   -   :ref:`EXT_ERROR support <msgpack_ext-error>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `Datetime support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-datetime-type>`__
```suggestion
    *   -   :ref:`Datetime support <msgpack_ext-datetime>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `Interval support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-interval-type>`__
```suggestion
    *   -   :ref:`Interval support <msgpack_ext-interval>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   `IPROTO_ID (feature discovery) <https://github.com/tarantool/doc/issues/2419>`__
```suggestion
    *   -   :ref:`IPROTO_ID (feature discovery) <box_protocol-id>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
>      *   -   `Session settings <https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/_session_settings/>`__
```suggestion
    *   -   :ref:`Session settings <box_space-session_settings>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
>      *   -   `box.session.push() responses <https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_session/push/>`__
```suggestion
    *   -   :ref:`box.session.push() responses <box_session-push`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
>      *   -   `SQL support <https://www.tarantool.io/en/doc/latest/reference/reference_sql/>`__
```suggestion
    *   -   :ref:`SQL support <reference_sql>`
```

2022-11-09 17:50 UTC, xuniq commented on doc/book/connectors/python.rst
>      *   -   `Interactive transactions <https://www.tarantool.io/en/doc/latest/book/box/stream/>`__
```suggestion
    *   -   :ref:`Interactive transactions <txn_mode_stream-interactive-transactions>`
```

2022-11-10 11:32 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +            <https://www.tarantool.io/en/doc/latest/getting_started/getting_started_python/>`__)
Fixed

2022-11-10 11:32 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +        -   `pip, deb, rpm, <https://github.com/tarantool/tarantool-python#download-and-install>`__
Fixed

2022-11-10 11:32 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `Decimal support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-decimal-type>`__
Fixed

2022-11-10 11:32 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `UUID support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-uuid-type>`__
Fixed

2022-11-10 11:32 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `EXT_ERROR support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-error-type>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `Datetime support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-datetime-type>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `Interval support <https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-interval-type>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   `IPROTO_ID (feature discovery) <https://github.com/tarantool/doc/issues/2419>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
>      *   -   `Session settings <https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/_session_settings/>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
>      *   -   `box.session.push() responses <https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_session/push/>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
>      *   -   `SQL support <https://www.tarantool.io/en/doc/latest/reference/reference_sql/>`__
Fixed

2022-11-10 11:33 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
>      *   -   `Interactive transactions <https://www.tarantool.io/en/doc/latest/book/box/stream/>`__
Fixed

2022-11-10 11:34 UTC, DifferentialOrange commented
Sorry about the anchors: I've just decided that since we used direct links in the previous version, it would be ok to add new as well. Replaced the link with `:ref:`s. Please, check the last row since I'm not sure that I used the anchor for Enterprise doc as it should be.

2022-11-10 13:07 UTC, xuniq requested changes
**About the Enterprise doc**

Currently, it's not possible to reference the enterprise docs from the doc repository using `:ref:` or `:doc:` directives. The enterprise anchors/file paths work only inside the corresponding repository. In this case, I suggest using the external link.

2022-11-10 13:07 UTC, xuniq commented on doc/book/connectors/python.rst
> +    *   -   :ref:`Encrypted connection (Tarantool Enterprise) <enterprise-iproto-encryption>`
```suggestion
    *   -   `Encrypted connection (Tarantool Enterprise) <https://www.tarantool.io/en/enterprise_doc/security/#enterprise-iproto-encryption>`__
```

2022-11-10 16:07 UTC, DifferentialOrange commented on doc/book/connectors/python.rst
> +    *   -   :ref:`Encrypted connection (Tarantool Enterprise) <enterprise-iproto-encryption>`
Ok, I got it. Thank you, fixed

2022-11-10 16:15 UTC, xuniq approved these changes

2022-11-16 15:20 UTC, merged