iproto: export IPROTO constants and features to Lua
tarantool/doc pull request #3766
Opened 2023-10-13 08:35 UTC by xuniq

Fixes #3241

2023-10-30 09:06 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/format.rst
> -array will have all the tuples of the result.
```suggestion
array has all the tuples of the result.
```

2023-10-30 09:09 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/keys.rst
> +            -   Unknown request or response type
```suggestion
- Unknown request or response type
```

Actually, this key is used only for IPROTO handler overriding, see tarantool/doc#3288. Would be nice to mention it here or not forget to come back later.

2023-10-30 09:09 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/keys.rst
> +Unknown request or response type.
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy requested changes

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    :param uint32_t     request_type: request type code from the ``iproto_type`` enumeration
I would also describe how `IPROTO_UNKNOWN` works separately. Or I would describe this on the separate page devoted to the Lua API (for `box.iproto.override`) and refer to this page here, i.e., `see details for <box.iproto.override>`.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    Send an :ref:`IPROTO <internals-iproto-format>` packet over the session's socket with the given MsgPack header
I guess you should mention that this feature only works for binary sessions (see [`box.session.type`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_session/type/)).

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/keys.rst
> +Unknown request or response type.
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/keys.rst
> +            -   Unknown request or response type
```suggestion
            -   Unknown request type
```

Actually, this key is used only for IPROTO handler overriding, so it would be nice to refer to it here.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/format.rst
> +array have all the tuples of the result.
```suggestion
array has all the tuples of the result.
```

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    :param iproto_handler_destroy_t destroy: IPROTO request handler destructor
I think you need to describe `iproto_handler_t` and `iproto_handler_destroy_t` separately (i.e., their signature).

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    :param void*    ctx: context passed to handler
This context is actually passed to both the `handler` and `destroy` callbacks (another reason to describe them separately).

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +*   send arbitrary IPROTO packets
I would refer to the APIs this can be achieved with, i.e., `box.iproto.override` plus `IPROTO_UNKNOWN` for the former, and `box.iproto.send` for the latter.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +*   override the behavior of the existing request types in binary protocol
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +To make this possible, the submodule exports all IPROTO :ref:`constants <box_iproto-constants>` and features to Lua.
I would refer to the IPROTO features [section](https://www.tarantool.io/ru/doc/latest/dev_guide/internals/iproto/keys/#iproto-features). 

> To make this possible

TBH, this is rather done for convenience. I would drop this line, as it doesn't provide useful information, IMHO.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +The constants are divided into several types:
```suggestion
The constants are divided into several groups:
```

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +Each type is located in the corresponding subnamespace without prefix.
```suggestion
Each group is located in the corresponding subnamespace without prefix.
```

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +*   IPROTO protocol features with the corresponding code (:ref:`box.iproto.feature <reference_lua-box_iproto_feature>`)
Maybe I would add a small example illustrating how this could be used (feel free to ignore this comment).

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/ballot.rst
> +    Available keys:
Doesn't this duplicate the binary protocol page? I doubt this is useful, while it increases maintenance costs (i.e., now each time a new protocol key is added, you have to update 2 pages). I would rather refer to binary protocol page (you already did it in the `learn more` line). Same comment for other pages describing each Lua IPROTO constant.

TL;DR: I suggest you drop the part about available keys here and from other pages and refer to the bianry protocol page.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/feature.rst
> +        Available features:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/flag.rst
> +    Available flags:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/key.rst
> +        Available keys:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/metadata.rst
> +    Available keys:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/override.rst
> +    :param iproto_handler_t     handler:
I guess you copy-pasted this from the C API, while this is not right. The Lua handler has a different interface than the C one, I would describe it separately.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/protocol_features.rst
> +    }
This exmaple looks strange, as if you assign the table by yourself instead of reading it. This example also doesn't seem to be reated to `box.iproto.protocol_version` you describe above — looks like you forgot to describe other attributes of `box.iproto.features`.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/protocol_version.rst
> +    Learn more: :ref:`IPROTO_ID <box_protocol-id>`.
Looks like you messed this up with the `doc/reference/reference_lua/box_iproto/protocol_features.rst` page.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/raft.rst
> +    Available keys:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/request_type.rst
> +    Available types:
Ditto.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/override.rst
> +    :return: 0 on success or -1 on error (check box_error_last())
Ditto. Actually it throws an error.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/send.rst
> +    :rtype: number
Actually, it throws an error.

2023-10-30 10:27 UTC, CuriousGeorgiy commented on doc/code_snippets/test/iproto/iproto_constants_export_test.lua
> +end
What is the point of this test?

Isn't it just copy-paste of [`gh_7894_export_iproto_constants_and_features_test.lua`](https://github.com/tarantool/tarantool/blob/master/test/box-luatest/gh_7894_export_iproto_constants_and_features_test.lua)?

2023-11-08 09:14 UTC, xuniq commented on doc/reference/reference_lua/box_iproto.rst
> +*   IPROTO protocol features with the corresponding code (:ref:`box.iproto.feature <reference_lua-box_iproto_feature>`)
Added an example

2023-11-09 12:44 UTC, CuriousGeorgiy approved these changes
Thanks for your fixes. I believe this is the last iteration, so I am approving this, but nevertheless please try to address my comments.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/box_protocol.rst
> +    request types (including the :ref:`unknown <box_iproto-unknown>` types).
> including the :ref:`unknown <box_iproto-unknown>` types

This is not a distinguished request type, but rather a constant for the `box.iproto.override` API that allows setting a handler for incoming requests that have an unknown type (image a Tarantool 3.0 instance accepting a `IPROTO_COOL_NEW_FEATURE` request from a Tarantool 4.0 instance).

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/requests.rst
> +            -   Unknown request type. The constant is used only for IPROTO handler :ref:`overriding <reference_lua-box_iproto_override>`.
Your description is not so precise, I would rather refer to the `internals-iproto-unknown` section below.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/internals/iproto/requests.rst
> +Unknown request type. The constant is used for overriding an unknown IPROTO request handler.
`Unknown request handler` sounds weird. This is a constant for overriding the handler for unknown IPROTO request types.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    If the Lua handler throws an exception, the behavior is similar to a remote procedure call.
```suggestion
    If a Lua handler throws an exception, the behavior is similar to that of a remote procedure call.
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    *   :errcode:`ER_PROC_LUA` -- the exception is thrown, diagnostic is not set.
```suggestion
    *   :errcode:`ER_PROC_LUA` -- an exception is thrown from a Lua handler, diagnostic is not set.
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    *  ``IPROTO_REQUEST_HANDLER_ERROR`` -- error, diagnostic must be set by handler
I would mention `box_error_set` or `box_error_raise` here.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +It enables to extend :ref:`IPROTO <box_protocol>` functionality from the Lua libraries.
```suggestion
It allows to extend the :ref:`IPROTO <box_protocol>` functionality from Lua.
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto.rst
> +*   :ref:`override the behavior <reference_lua-box_iproto_override>` of the existing request types in the binary protocol
And unknown request types.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    The signature of a destructor function (the ``destroy`` parameter):
Please describe when this destructor is called.

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/dev_guide/reference_capi/box.rst
> +    *  ``IPROTO_REQUEST_HANDLER_FALLBACK`` -- fallback to the system handler
```suggestion
    *  ``IPROTO_REQUEST_HANDLER_FALLBACK`` -- fallback to the system (default) handler
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/override.rst
> +                                    ``box.iproto.type.UNKNOWN``) -- override the existing request type.
```suggestion
                                    ``box.iproto.type.UNKNOWN``) -- override the existing request type handler.
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/override.rst
> +                                *   ``box.iproto.type.UNKNOWN`` -- override an unknown request type.
```suggestion
                                    ``box.iproto.type.UNKNOWN``) -- override the handler of unknown request types.
```

2023-11-09 12:44 UTC, CuriousGeorgiy commented on doc/reference/reference_lua/box_iproto/override.rst
> +                             to the system handler.
I would mention, that one can indicate an error by throwing an exception. In this sense, retuning `false` means falling back to the system (default) handler, and this is not always a failure, it's just one of the possible options.

2023-11-17 08:55 UTC, andreyaksenov requested changes

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto.rst
> +*   :ref:`parse the unknown IPROTO requests types <reference_lua-box_iproto_override>`
```suggestion
*   :ref:`parse unknown IPROTO request types <reference_lua-box_iproto_override>`
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto.rst
> +*   :ref:`RAFT key <reference_lua-box_iproto_raft>` (:ref:`IPROTO_TERM <internals-iproto-keys-term>`)
As I see, this page already contains info, examples, and links to IPROTO internals for all namespaces listed in this list. I would think about dropping separate pages for API members (such as [box.iproto.key](https://docs.d.tarantool.io/en/doc/gh-3241-iproto/reference/reference_lua/box_iproto/key/)) and moving all these descriptions to the [API reference](https://docs.d.tarantool.io/en/doc/gh-3241-iproto/reference/reference_lua/box_iproto/#api-reference) section. But this up to you: I just like the [Every page is page one](https://idratherbewriting.com/trends/trends-to-follow-or-forget-every-page-is-page-one.html) approach  to give a user all the context at once :)

In a case you'll decide to merge all this, we can add separate subsections for namespaces, properties, and functions to `API reference` .

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto.rst
> +*   :ref:`request type <reference_lua-box_iproto_type>` (:ref:`IPROTO_OK <internals-iproto-ok>`)
Am I correct that `IPROTO_OK` is one example of a request type? If yes, we can emphasise this somehow (`for example, IPROTO_OK`) and just give a link to the full list of keys.

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto.rst
> +    }
Could you please reformat code to add indentation inside curly brackets?
<img width="550" alt="image" src="https://github.com/tarantool/doc/assets/38073144/b7e4ac92-baa9-44c1-9067-5a87c3d60c91">

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/key.rst
> +    The ``box.iproto.key`` namespace contains all available request keys, except :ref:`raft <reference_lua-box_iproto_raft>`,
I'd remove `The ``box.iproto.key`` namespace` here and for other namespaces as this repeats `box.iproto.key` for a third time.

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto.rst
> +            - Current IPROTO protocol version
```suggestion
            - The current IPROTO protocol version
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/protocol_version.rst
> +    Current IPROTO protocol version of the server.
```suggestion
    The current IPROTO protocol version of the server.
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/override.rst
> +        local function iproto_select_handler_lua(sid, header, body)
Too many spaces are used for indentation. Here is how the IDE formats this code by default:
<img width="691" alt="image" src="https://github.com/tarantool/doc/assets/38073144/ff8fe8f8-7353-4689-8fb4-67b21b2720bf">

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/send.rst
> +                        {data = 1}))
Hmm, looks like a syntax error might be here, please double-check these examples.
<img width="874" alt="image" src="https://github.com/tarantool/doc/assets/38073144/663d628d-24d0-4e80-9b6f-61df7cef43ad">

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/override.rst
> +                             *  ``sid`` (number): current IPROTO session identifier (see :ref:`box.session.id() <box_session-id>`)
```suggestion
                             *  ``sid`` (number): the current IPROTO session identifier (see :ref:`box.session.id() <box_session-id>`)
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/send.rst
> +    :param number sid: IPROTO session identifier (see :ref:`box.session.id() <box_session-id>`)
```suggestion
    :param number sid: the IPROTO session identifier (see :ref:`box.session.id() <box_session-id>`)
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_info/schema_version.rst
> +    See also :ref:`IPROTO_SCHEMA_VERSION <internals-iproto-keys-schema_version>`
```suggestion
    See also: :ref:`IPROTO_SCHEMA_VERSION <internals-iproto-keys-schema_version>`
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/dev_guide/reference_capi/box.rst
>      :return: 0 or -1 if there is no session
```suggestion
    :return: the session identifier; 0 or -1 if there is no session
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/dev_guide/internals/iproto/requests.rst
> +            -   Unknown request type
```suggestion
            -   An unknown request type
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/dev_guide/internals/iproto/requests.rst
> +Unknown request type. The constant is used to override the handler of unknown IPROTO request types.
```suggestion
An unknown request type. The constant is used to override the handler of unknown IPROTO request types.
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/override.rst
> +                             In this case, the return value is ``false``, but this does not always means a failure.
```suggestion
                             In this case, the return value is ``false``, but this does not always mean a failure.
```

2023-11-17 08:55 UTC, andreyaksenov commented on doc/reference/reference_lua/box_iproto/send.rst
> +    *   :errcode:`ER_MEMORY_ISSUE` -- out of memory limit has been reached.
```suggestion
    *   :errcode:`ER_MEMORY_ISSUE` -- out-of-memory limit has been reached.
```

2023-11-20 09:08 UTC, andreyaksenov approved these changes

2023-11-20 13:48 UTC, merged

2023-11-20 13:50 UTC, xuniq commented
> Thanks for your fixes. I believe this is the last iteration, so I am approving this, but nevertheless please try to address my comments.

@CuriousGeorgiy Thank you for the review!