Add TCM clusters doc
tarantool/doc pull request #3925
Opened 2023-12-12 05:50 UTC by p7nov

Resolves #3631

2023-12-14 14:21 UTC, filonenko-mikhail approved these changes

2023-12-15 07:27 UTC, andreyaksenov requested changes

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_connect_clusters.rst
> +    or a :ref:`Tarantool user <authentication>` and .
```suggestion
    or a :ref:`Tarantool user <authentication>`.
```

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_connect_clusters.rst
> +If you already have a cluster and want connect it to |tcm|,
```suggestion
If you already have a cluster and want to connect it to |tcm|,
```

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_connect_clusters.rst
> +        a Grafana dashboard that monitors the cluster metrics, ot a syslog server
```suggestion
        a Grafana dashboard that monitors the cluster metrics, or a syslog server
```

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_connect_clusters.rst
> +        a Grafana dashboard that monitors the cluster metrics, ot a syslog server
```suggestion
        a Grafana dashboard that monitors the cluster metrics, or a syslog server
```

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_connect_clusters.rst
> +    thing that is changed is that it's no longer shown in |tcm|.
```suggestion
    thing that changes is that it's no longer shown in |tcm|.
```

2023-12-15 07:27 UTC, andreyaksenov commented on doc/reference/tooling/tcm/tcm_cluster_config.rst
> +To reset an saved configuration file, click the **Reset** button beside the filename.
```suggestion
To reset a saved configuration file, click the **Reset** button beside the filename.
```

2023-12-15 07:49 UTC, andreyaksenov approved these changes

2023-12-15 07:51 UTC, merged