Update tt commands descriptions to 2.1.2
tarantool/doc pull request #4039
Opened 2024-02-13 09:08 UTC by p7nov

Resolves #3999 https://github.com/tarantool/enterprise_doc/issues/260 https://github.com/tarantool/enterprise_doc/issues/259

2024-02-13 10:07 UTC, psergee approved these changes
Thank you for the patch. lgtm.

2024-02-13 10:07 UTC, psergee commented on doc/reference/tooling/tt_cli/start.rst
> +*   ``instances yml`` -- a file that defines the list of cluster instances to run
```suggestion
*   ``instances.yml`` -- a file that defines the list of cluster instances to run
```

2024-02-13 12:30 UTC, andreyaksenov requested changes
Please see my suggestions below

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/start.rst
> +Such instances are based on Lua code provided in files inside the ``instances_enabled`
```suggestion
Such instances are based on Lua code provided in files inside the ``instances_enabled``
```

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/start.rst
> +    It can either contain an explicit configuration in the YAML format, or point
```suggestion
    It can either contain an explicit configuration in the YAML format or point
```

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/start.rst
> +``tt start`` can start single Tarantool instances without cluster configurations.
> without cluster configurations

I'd clarify this description with a link to the `Configuration in code` topic: 

https://www.tarantool.io/en/doc/latest/concepts/configuration/configuration_code/

Now it is hard to understand that this instruction is for a legacy approach. `

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/stop.rst
> +When called without arguments, stops all running applications in the current environment.
I'd add a link to `tt start` somewhere to allow a reader get more context. (Here and in other pages related to starting/stopping instances - status/restart/...)

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/create.rst
>  To change the application location, use the ``-dst`` flag.
Let's add a link to the `dst` flag. (and maybe change flag -> option :) )

2024-02-13 12:30 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/start.rst
> +Cluster application
As we discussed, let's consider restructuring of such pages to reflect that multi-instance apps can both use new and old config.

2024-02-14 04:27 UTC, p7nov commented on doc/reference/tooling/tt_cli/create.rst
>  To change the application location, use the ``-dst`` flag.
Changed `flag` to `option` across the page.

Not sure we need links to options on the same page with their reference. There is a lot of such mentionings in usage explanation and we don't normally add links (on the same page).

2024-02-14 07:40 UTC, andreyaksenov approved these changes

2024-02-14 07:40 UTC, andreyaksenov commented on doc/reference/tooling/tt_cli/restart.rst
> + *   Restart only the ``master`` instance of the ``app`` application  with automatic confirmation:
<img width="700" alt="image" src="https://github.com/tarantool/doc/assets/38073144/bd58b46b-b563-44bc-9ab0-202efb5ccf80">


```suggestion
*   Restart only the ``master`` instance of the ``app`` application  with automatic confirmation:
```

2024-02-14 07:53 UTC, merged