Add varbinay docs
tarantool/doc pull request #4405
Opened 2024-08-05 05:20 UTC by p7nov

Resolves #3551

2024-08-05 12:11 UTC, locker approved these changes

2024-08-05 14:26 UTC, andreyaksenov requested changes
Several comments from me.

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +    This behavior is different from what is was before Tarantool 3.0.
```suggestion
    This behavior is different from what it was before Tarantool 3.0.
```

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +        A ``varbinary`` object equals to a another ``varbinary`` object or a string if it
```suggestion
        A ``varbinary`` object equals to another ``varbinary`` object or a string if it
```

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/compat/binary_data_decoding.rst
> +TBD
Don't quite understand what does that mean.

2024-08-05 14:26 UTC, andreyaksenov commented on doc/code_snippets/test/varbinary/varbinary_test.lua
> +print(#varbinary.new('\xFF\xFE')) -- 2
Are any differences between creating a varbinary object from a string value (`varbinary.new('data')` above) and from such HEX representation (`varbinary.new('\xFF\xFE')`)? Looks a bit inconsistent that we pay more attention to the first one.

BTW, found out that `tostring` doesn't work for the latter case:

```
application:instance001> tostring(varbinary.new('\xFF\xFE'))
---
- error: 'console: exception while formatting the output: "expected SCALAR, SEQUENCE-START,
    MAPPING-START, or ALIAS"'
...
```

So, it looks that such objects differ to some extent.

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +        ...
Getting the error on an attempt to execute this code (in both tt and tarantool console):

<img width="828" alt="image" src="https://github.com/user-attachments/assets/5bc84d3e-99c4-44bf-a830-b6b7853aa1a7">

BTW, I'd add a link to [msgpack](https://www.tarantool.io/en/doc/latest/reference/reference_lua/msgpack/) before the examples, so a reader can understand how to load the msgpack module.

2024-08-05 14:26 UTC, andreyaksenov commented on doc/code_snippets/test/varbinary/varbinary_test.lua
> +bin = varbinary.new('data')
Nit:

```suggestion
local bin = varbinary.new('data')
```

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +    :rtype: varbinary
```suggestion
    :rtype: cdata
```

<img width="483" alt="image" src="https://github.com/user-attachments/assets/b3f82b4b-a7f9-4471-9da7-a3e0a890e4a9">

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +    :param cdata data: a ``cdata`` pointer
Weird rendering of arguments, in particular, `data (cdata) – a string object`:

<img width="729" alt="image" src="https://github.com/user-attachments/assets/c0e0c056-8d9f-4cda-b5b3-211e0b2b6db5">

I believe two separate function definitions would work better.

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +.. _varbinary-module-overview:
```suggestion
Module varbinary
================

**Since:** :doc:`3.0.0 </release/3.0.0>`

.. _varbinary-module-overview:
```

2024-08-05 14:26 UTC, andreyaksenov commented on doc/reference/reference_lua/varbinary.rst
> +        :rtype: string
```suggestion
        Returns a ``varbinary`` object data in a plain string.
        
        Defines the ``tostring()`` function for ``varbinary`` objects.

        :rtype: string
```

2024-08-06 06:08 UTC, p7nov commented on doc/reference/reference_lua/varbinary.rst
> +        ...
@locker could you help? I'm getting the same error (Tarantool 3.1.1, macOS, x86_64). Even without `msgpack`  there are issues with hex values (copied from an example in the [doc task](https://github.com/tarantool/doc/issues/3551)):

```
tarantool> '\xFF\xFE'
---
- error: 'console: exception while formatting the output: "expected SCALAR, SEQUENCE-START,
    MAPPING-START, or ALIAS"'
...
```

2024-08-06 07:48 UTC, locker commented on doc/reference/reference_lua/varbinary.rst
> +        ...
Is this the built-in console or `tt`? I don't get any errors with the built-in console:

```
$ tarantool -i
Tarantool 3.1.1-0-g7e72167dfde0
type 'help' for interactive help
tarantool> '\xFF\xFE'
---
- "\xFF\xFE"
...
```

2024-08-06 07:55 UTC, p7nov commented on doc/reference/reference_lua/varbinary.rst
> +        ...
The built-in console. @andreyaksenov encountered the same error in `tt` as well, see the root comment.

Rechecked this on Ubuntu - works fine. A macOS-specific bug?

2024-08-06 07:57 UTC, locker commented on doc/reference/reference_lua/varbinary.rst
> +        ...
Looks like it. Please [file a bug](https://github.com/tarantool/tarantool/issues/new?assignees=&labels=bug&projects=&template=bug_report.md).

2024-08-06 08:45 UTC, p7nov commented on doc/code_snippets/test/varbinary/varbinary_test.lua
> +print(#varbinary.new('\xFF\xFE')) -- 2
Nothing specific, both string representations just work.
An error is caused by the same bug you wrote in another comment. Filed an [issue](https://github.com/tarantool/tarantool/issues/10373).

2024-08-06 09:59 UTC, andreyaksenov approved these changes
great job, lgtm

2024-08-06 10:17 UTC, merged