datetime: describe relational operators
tarantool/doc pull request #4413
Opened 2024-08-06 14:20 UTC by ligurio

Follows up commit de58780f7f33
("Add a new section for the datetime module with the description of its main functions and methods").

Datetime comparison has been added in [1] (since 2.10.0-beta2), interval comparison has been added in commit [2]
(since 2.11.0-rc1).

1. https://github.com/tarantool/tarantool/commit/43e10ed3494998b5f07af93b83307f27a9fb755a
2. https://github.com/tarantool/tarantool/commit/65a3c17f283acd89af252b4406ba9e93a034ccab

Folows up #2411

2024-08-06 14:44 UTC, andreyaksenov requested changes
Please see my suggestions below

2024-08-06 14:44 UTC, andreyaksenov commented on doc/reference/reference_lua/datetime.rst
> +
```suggestion
If you need to compare the ``datetime`` and ``interval`` object values, you can use standard Lua relational operators: ``==``, ``~=``, ``>``, ``<``, ``>=``, and ``<=``. These operators use the overloaded ``__eq``, ``__lt``, and ``__le`` metamethods to compare values.

```

2024-08-06 14:44 UTC, andreyaksenov commented on doc/reference/reference_lua/datetime.rst
> +Support of relational operators for ``interval`` objects has been added since: :doc:`2.11.0 </release/2.11.0>`.
```suggestion
Support for relational operators for ``interval`` objects has been added since :doc:`2.11.0 </release/2.11.0>`.
```

2024-08-06 14:44 UTC, andreyaksenov commented on doc/reference/reference_lua/datetime.rst
> +            tarantool>
```suggestion
**Example 1:**

..  code-block:: tarantoolsession

    tarantool> dt1 = datetime.now()
    ---
    ...

    tarantool> dt2 = datetime.now()
    ---
    ...

    tarantool> dt1 == dt2
    ---
    - false
    ...

    tarantool> dt1 < dt2
    ---
    - true
    ...

**Example 2:**

..  code-block:: tarantoolsession

    tarantool> iv1 = datetime.interval.new({month = 1})
    ---
    ...

    tarantool> iv2 = datetime.interval.new({month = 2})
    ---
    ...

    tarantool> iv1 < iv2
    ---
    - true
    ...
```

2024-08-06 18:47 UTC, ligurio commented
Fixed datetime objects in example:

```diff
--- a/doc/reference/reference_lua/datetime.rst
+++ b/doc/reference/reference_lua/datetime.rst
@@ -978,11 +978,11 @@ Support for relational operators for ``interval`` objects has been added since :
 
 ..  code-block:: tarantoolsession
 
-    tarantool> dt1 = datetime.now()
+    tarantool> dt1 = datetime.new { year = 2010 }
     ---
     ...
 
-    tarantool> dt2 = datetime.now()
+    tarantool> dt2 = datetime.new { year = 2024 }
     ---
     ...
 ```

2024-08-07 06:51 UTC, andreyaksenov approved these changes
LGTM, thanks for your contribution!

2024-08-07 08:37 UTC, merged